In [ ]:
import nltk

In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
!pip install Sastrawi

     |████████████████████████████████| 209 kB 5.3 MB/s 


In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.tokenize import word_tokenize

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

# create stemmer
factory = StemmerFactory()
stemmer = factory.create_stemmer()

# Add text
text = "Saya akan makanan nasi di warung"
kata =text.lower()
tokens = word_tokenize(kata)
print(tokens)


english_stopwords = stopwords.words('indonesian')
list=['makan', 'nasi']
english_stopwords.extend(list)
tokens_wo_stopwords = [t for t in tokens if t not in english_stopwords]
print(tokens_wo_stopwords)

print("Text without stop words:", " ".join(tokens_wo_stopwords))
sting=" ".join(tokens_wo_stopwords)
print(sting)
output   = stemmer.stem(sting)
print(output)

['saya', 'akan', 'makanan', 'nasi', 'di', 'warung']
['makanan', 'warung']
Text without stop words: makanan warung
makanan warung
makan warung


In [ ]:
import numpy as np
#import PyPDF2
#import doctext
import sys
from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer

In [ ]:
cv = CountVectorizer()
cv_demo = CountVectorizer() 


In [ ]:
demo_teks = ["Saya suka yang baik baik, kamu suka yang jelek jelek", "Saya tidak baik "] 
cv_matrix = cv.fit_transform(demo_teks)
res_demo = cv_demo.fit_transform(demo_teks)
print('Arraynya adalah {}'.format(res_demo.toarray()))
print('Feature list: {}'.format(cv_demo.get_feature_names_out()))

Arraynya adalah [[2 1 1 1 1 0]
 [1 0 0 1 0 1]]
Feature list: ['baik' 'jelek' 'kamu' 'saya' 'suka' 'tidak']


In [ ]:
normal_matrix = TfidfTransformer().fit_transform(res_demo)

In [ ]:
print(normal_matrix.toarray())

[[0.60506143 0.42519636 0.42519636 0.30253071 0.42519636 0.        ]
 [0.50154891 0.         0.         0.50154891 0.         0.70490949]]


In [24]:
!pip install docx-text

In [25]:
!pip install PyPDF3

In [26]:
import numpy as np
import PyPDF3
import doctext
import sys
from IPython.display import Image

In [27]:
import matplotlib.pyplot as plt
%matplotlib inline 

In [28]:
import networkx as nx

In [29]:
from nltk.tokenize.punkt import PunktSentenceTokenizer

In [30]:
from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer

In [31]:
!pwd

/content


In [34]:
%cd /content/drive/MyDrive/Colab Notebooks

/content/drive/MyDrive/Colab Notebooks


In [36]:
pdfFileObj = open('datatext.pdf', 'rb') # digantikan hasil crawling anda
pdfReader = PyPDF3.PdfFileReader(pdfFileObj)
pageObj = pdfReader.getPage(0)
document = pageObj.extractText()

In [37]:
doc_tokenizer = PunktSentenceTokenizer()
sentences_list = doc_tokenizer.tokenize(document)

In [38]:
!pip install sastrawi

     |████████████████████████████████| 209 kB 6.6 MB/s 


In [39]:
import string 
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory# create stemmer
factory = StemmerFactory()
stemmer = factory.create_stemmer()

In [40]:
import re # impor modul regular expressionkalimat = "Berikut ini adalah 5 negara dengan pendidikan terbaik di dunia adalah Korea Selatan, Jepang, Singapura, Hong Kong, dan Finlandia."
dokumenre=[]
for i in sentences_list:
    hasil = re.sub(r"\d+", "", i)
    dokumenre.append(hasil) 
print(dokumenre)

['Saya\n \nsuka\n \nyang\n \nbaik\n \nb\naik,\n \nkamu\n \nsuka\n \nyang\n \njel\nek jelek.', 'Saya\n \ntidak\n \nsukan yang jelek\n.']


In [41]:
dokumen=[]
for i in dokumenre:
    hasil =  i.replace('\n','') 
    dokumen.append(hasil) 
print(dokumen)

['Saya suka yang baik baik, kamu suka yang jelek jelek.', 'Saya tidak sukan yang jelek.']


In [42]:
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from nltk.tokenize import word_tokenize
factory = StopWordRemoverFactory()
stopword  = factory.create_stop_word_remover()


In [43]:
a=len(dokumen)
dokumenstop=[]
for i in range(0, a):
    sentence = stopword.remove(dokumen[i])
    dokumenstop.append(sentence)
print(dokumenstop)   

['Saya suka baik baik, kamu suka jelek jelek.', 'Saya sukan jelek.']


In [44]:
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from nltk.tokenize import word_tokenize
factory = StopWordRemoverFactory()
dokumenstop=[]
for i in dokumen:
    output = i.translate(str.maketrans("","",string.punctuation))
    dokumenstop.append(output)
    
print(dokumenstop)

['Saya suka yang baik baik kamu suka yang jelek jelek', 'Saya tidak sukan yang jelek']


In [45]:
factory = StemmerFactory()
stemmer = factory.create_stemmer()
dokumenstem=[]
for i in dokumenstop:
    output = stemmer.stem(i)
    dokumenstem.append(output)
print(dokumenstem)

['saya suka yang baik baik kamu suka yang jelek jelek', 'saya tidak sukan yang jelek']


In [62]:
vectorizer = CountVectorizer(min_df=1)
bag = vectorizer.fit_transform(dokumenstem)


In [63]:
print(vectorizer.vocabulary_)

{'saya': 3, 'suka': 4, 'yang': 7, 'baik': 0, 'kamu': 2, 'jelek': 1, 'tidak': 6, 'sukan': 5}


In [64]:
print(vectorizer.get_feature_names_out())

['baik' 'jelek' 'kamu' 'saya' 'suka' 'sukan' 'tidak' 'yang']


In [65]:
matrik_vsm=bag.toarray()
#print(matrik_vsm)
matrik_vsm.shape

(2, 8)

In [66]:
matrik_vsm[0]

array([2, 2, 1, 1, 2, 0, 0, 2])

In [67]:
import pandas as pd
a=vectorizer.get_feature_names_out()

In [77]:
print(len(matrik_vsm[:,1]))
#dfb =pd.DataFrame(data=matrik_vsm,index=df,columns=[a])
dfb =pd.DataFrame(data=matrik_vsm,index=list(range(1, len(matrik_vsm[:,1])+1, )),columns=[a])
dfb

2


baik jelek kamu saya suka sukan tidak yang
1    2     2    1    1    2     0     0    2
2    0     1    0    1    0     1     1    1

### Kata yang paling besar kata (pada) /term frequency dalam dokumen ketiga,paling sering muncul kata tersebut, tetapi setelah ditransformasi kedalam  tf-idfs, kata tersebut relatif kecil nilai tf-idfnya. Perhatikan kemunculan kata tersebut di  (discriminatory information).

##  $$\text{idf} (t,d) = ln\frac{1 + n_d}{1 + \text{df}(d, t)}$$

$ \text{df}(d, t) =$  banyaknya dokumen yang mengandung term t    


$ \text n_d =  $ banyaknya dokumen  


Persamaan tf-idf yang diimplementasikan dalam scikit-learn adalah:

$$\text{tf-idf}(t,d) = \text{tf}(t,d) \times (\text{idf}(t,d)+1)$$


$ \text{tf}(t,d) $ banyak kemunculan term dalam suatu dokumen

Kemudian dinormalisasi



$$v_{\text{norm}} = \frac{v}{||v||^2} = \frac{v}{\sqrt{v_{1}^{2} + v_{2}^{2} + \dots + v_{n}^{2}}} = \frac{v}{\big (\sum_{i=1}^{n} v_{i}^{2}\big)^\frac{1}{2}}$$





In [69]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf = TfidfTransformer(use_idf=True,norm='l2',smooth_idf=True)
tf=tfidf.fit_transform(vectorizer.fit_transform(dokumenstem)).toarray()

In [70]:
dfb =pd.DataFrame(data=tf,index=list(range(1, len(tf[:,1])+1, )),columns=[a])
dfb

baik     jelek      kamu      saya      suka     sukan     tidak  \
1  0.543202  0.386492  0.271601  0.193246  0.543202  0.000000  0.000000   
2  0.000000  0.379303  0.000000  0.379303  0.000000  0.533098  0.533098   

       yang  
1  0.386492  
2  0.379303

In [71]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from collections import Counter
corpus = [
     'This is the first document.',
     'This document is the second document.',
     'And this is the third one.',
     'Is this the first document?',
 ]
print(corpus)
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())

z=X.toarray()
#term frequency is printed
print(z)

vectorizer1 = TfidfVectorizer(min_df=1)
X1 = vectorizer1.fit_transform(corpus)
idf = vectorizer1.idf_
print (dict(zip(vectorizer1.get_feature_names(), idf)))
#printing idf
print(X1.toarray())
#printing tfidf

['This is the first document.', 'This document is the second document.', 'And this is the third one.', 'Is this the first document?']
['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]
{'and': 1.916290731874155, 'document': 1.2231435513142097, 'first': 1.5108256237659907, 'is': 1.0, 'one': 1.916290731874155, 'second': 1.916290731874155, 'the': 1.0, 'third': 1.916290731874155, 'this': 1.0}
[[0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]
 [0.         0.6876236  0.         0.28108867 0.         0.53864762
  0.28108867 0.         0.28108867]
 [0.51184851 0.         0.         0.26710379 0.51184851 0.
  0.26710379 0.51184851 0.26710379]
 [0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]]
